# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af463cb726dd6554da6be48358911e9da15f17561be9d5ac1c4738513c613e2e6b6a09cc80dbefc4dbd2844abd6e7e37865f4b23d748da3ba787b7bd22d7e115

test:
  secret_key_base: c6b37d5aff6551da334e4206710acf9e1b5a9f0c0a370b90cb1e9181627610b4f1991a1fdd72ce55a27f780cf80d20babf4242ea255a6e8a9ffa841575f930f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
